package catalog.dao;

import catalog.model.Product;

import java.sql.*;

public class ProductDAO {
    private String jdbcURL = "jdbc:mysql://localhost:3306/catalog_db2";
    private String jdbcUsername = "root";
    private String jdbcPassword = "root";

    private static final String INSERT_PRODUCT_SQL =
            "INSERT INTO product (name, sku, categoryName, size, price, discount, discountPrice) VALUES (?, ?, ?, ?, ?, ?, ?)";

    public ProductDAO() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // MySQL Connector/J driver class
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    protected Connection getConnection() throws SQLException {
        return DriverManager.getConnection(jdbcURL, jdbcUsername, jdbcPassword);
    }

    public boolean insertProduct(Product product) throws SQLException {
        boolean rowInserted = false;

        try (Connection connection = getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(INSERT_PRODUCT_SQL)) {

            // Note: productID assumed auto-generated by DB, so not included here

            preparedStatement.setString(1, product.getName());
            preparedStatement.setString(2, product.getSku());
            preparedStatement.setString(3, product.getCategoryName());
            preparedStatement.setString(4, product.getSize());
            preparedStatement.setBigDecimal(5, product.getPrice());
            preparedStatement.setInt(6, product.getDiscount());
            preparedStatement.setBigDecimal(7, product.getDiscountPrice());

            rowInserted = preparedStatement.executeUpdate() > 0;
        }

        return rowInserted;
    }
}
